namespace:
  name: demo
 
service:
  port: 8111
  type: ClusterIP

image:
  repository: techtrends
  tag: lastest
  pullPolicy: IfNotPresent

replicaCount: 3

resources:
  requests:
    cpu: 50m
    memory: 256Mi


