namespace:
  name: staging 
 
service:
  port: 8111
  type: ClusterIP

image:
  repository: techtrends 
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 50m
    memory: 128Mi
