## provide the name of the namespace
namespace:
  name: sandbox

## service information
service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

## define the image to execute with the Deployment 
image:
  repository: techtrends
  tag: latest
  pullPolicy: IfNotPresent

## set the number of replicas for an application 
replicaCount: 1

## resources
resources:
  requests:
    memory: 64Mi
    cpu: 250m
  limits: 
    memory: 128Mi
    cpu: 500m

## container port
containerPort: 3111

## liveness and readiness
livenessProbe: 
  path: /healthz
readinessProbe: 
  path: /healthz